/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemagestorprestamos.presentacion;

import itson.sistemagestorprestamos.fachada.empleadoFachada;
import itson.sistemagestorprestamos.utilidades.SesionIniciada;
import itson.sistemasgestorprestamos.DTO.GuardarEmpleadoDTO;
import itson.sistemasgestorprestamos.DTO.SesionEmpleadoDTO;
import itson.sistemasgestorprestamos.Negocio.NegocioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Camila Zubía
 */
public class AgregarEmpleadoFrm extends javax.swing.JFrame {
    
    private AdministrarEmpleadosFrm adminEmpleadoFrm;

    /**
     * Creates new form ConsultaPrestamoFrm
     */
    public AgregarEmpleadoFrm(AdministrarEmpleadosFrm adminEmpleadoFrm) {
        initComponents();
        this.adminEmpleadoFrm = adminEmpleadoFrm;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    empleadoFachada empleado = new empleadoFachada();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        tituloLbl = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtFieldNombre = new javax.swing.JTextField();
        txtFieldApellidoP = new javax.swing.JTextField();
        txtFieldApellidoM = new javax.swing.JTextField();
        txtFieldUsuario = new javax.swing.JTextField();
        txtFieldContraseña = new javax.swing.JTextField();
        btnSiguienteEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1077, 630));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setName("Separador"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(1077, 2));

        tituloLbl.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        tituloLbl.setText("AGREGAR EMPLEADO");

        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaanterior2.png"))); // NOI18N
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("Nombre(s):");

        lblApellidoP.setBackground(new java.awt.Color(255, 255, 255));
        lblApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoP.setText("Apellido paterno:");

        lblApellidoM.setBackground(new java.awt.Color(255, 255, 255));
        lblApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidoM.setText("Apellido materno:");

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");

        txtFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFieldApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldApellidoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFieldApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldApellidoPActionPerformed(evt);
            }
        });

        txtFieldApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldApellidoM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUsuarioActionPerformed(evt);
            }
        });

        txtFieldContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSiguienteEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSiguienteEmpleado.setText("SIGUIENTE");
        btnSiguienteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(tituloLbl))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseña)
                            .addComponent(lblApellidoP)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidoM)
                            .addComponent(lblUsuario))
                        .addGap(39, 39, 39)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(btnSiguienteEmpleado))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoP))
                .addGap(36, 36, 36)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoM))
                .addGap(37, 37, 37)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(34, 34, 34)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(45, 45, 45)
                .addComponent(btnSiguienteEmpleado)
                .addGap(27, 27, 27)
                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUsuarioActionPerformed

    private void btnSiguienteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteEmpleadoActionPerformed
        // TODO add your handling code here:
        String nombre = txtFieldNombre.getText();
        String apellidoP = txtFieldApellidoP.getText();
        String apellidoM = txtFieldApellidoM.getText();
        String usuario = txtFieldUsuario.getText();
        String contraseña = txtFieldContraseña.getText();
        // esto se va a mover luego al frm agregarCuentaEmpleado
        try {
            SesionEmpleadoDTO jefe = SesionIniciada.getInstancia().getEmpleado();
            int iddepartamento = jefe.getId();
            GuardarEmpleadoDTO empleadoGuardar = new GuardarEmpleadoDTO(nombre, apellidoP, apellidoM, usuario, contraseña, iddepartamento);
            empleado.guardar(empleadoGuardar);
            new AgregarCuentaEmpleadoFrm(this).setVisible(true);
            this.setVisible(false);

        } catch (NegocioException ex) {
            Logger.getLogger(AgregarEmpleadoFrm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error al abrir la siguiente pagina");
        }

    }//GEN-LAST:event_btnSiguienteEmpleadoActionPerformed

    private void txtFieldApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldApellidoPActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        adminEmpleadoFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnSiguienteEmpleado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JTextField txtFieldApellidoM;
    private javax.swing.JTextField txtFieldApellidoP;
    private javax.swing.JTextField txtFieldContraseña;
    private javax.swing.JTextField txtFieldNombre;
    private javax.swing.JTextField txtFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
