/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemagestorprestamos.presentacion;

import itson.sistemagestorprestamos.fachada.CuentaDepartamentoFachada;
import itson.sistemagestorprestamos.fachada.prestamoFachada;
import itson.sistemagestorprestamos.utilidades.SesionIniciada;
import itson.sistemasgestorprestamos.DTO.FiltroDTO;
import itson.sistemasgestorprestamos.DTO.SesionEmpleadoDTO;
import itson.sistemasgestorprestamos.Negocio.NegocioException;
import itson.sistemasgestorprestamos.dominios.CuentasDepartamentosDominio;
import itson.sistemasgestorprestamos.dominios.PrestamosDominio;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Camila Zubía
 */
public class ConsultaPrestamoFrm extends javax.swing.JFrame {

    private AdministrarPrestamosFrm adminPrestamosFrm;
    int id;
    prestamoFachada prestamo = new prestamoFachada();

    /**
     * Creates new form ConsultaPrestamoFrm
     *
     * @param adminPrestamosFrm
     * @param id
     */
    public ConsultaPrestamoFrm(AdministrarPrestamosFrm adminPrestamosFrm, int id) throws NegocioException {
        initComponents();
        this.adminPrestamosFrm = adminPrestamosFrm;
        cargarCuentasComboBox();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.id = id;
        mostrarInfo();
    }

    SesionEmpleadoDTO jefe = SesionIniciada.getInstancia().getEmpleado();
    CuentaDepartamentoFachada cuenta = new CuentaDepartamentoFachada();

    private void cargarCuentasComboBox() {
        SesionEmpleadoDTO empleado = SesionIniciada.getInstancia().getEmpleado();
        int id = empleado.getId();

        FiltroDTO filtro = new FiltroDTO(10, 0, String.valueOf(id));

        try {
            List<CuentasDepartamentosDominio> cuentas = cuenta.buscarCuentasDepartamentosPorId(filtro);
            comboBoxCuentas.removeAllItems();

            for (CuentasDepartamentosDominio cuenta : cuentas) {
                System.out.println("Cuenta: " + cuenta.getClabe());
                comboBoxCuentas.addItem(cuenta.getClabe());
            }

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar cuentas: " + e.getMessage());
        }
    }

    private void mostrarInfo() throws NegocioException {
        try {
            PrestamosDominio prestamoInfo = prestamo.buscarPorId(id);

            if (prestamoInfo != null) {
                String info = "ID del prestamo: " + prestamoInfo.getId() + "\n"
                        + "Fecha: " + prestamoInfo.getFechaHora() + "\n"
                        + "Monto: " + prestamoInfo.getMonto() + "\n"
                        + "Estatus: " + prestamoInfo.getEstatus() + "\n"
                        + "ID del tipo: " + prestamoInfo.getTipoPrestamo() + "\n"
                        + "ID de la cuenta del departamento: " + prestamoInfo.getCuentaDepartamento() + "\n"
                        + "ID de la cuenta del empleado: " + prestamoInfo.getCuentaEmpleado();
                txtAreaComprobante.setText(info);
            }
        } catch (NegocioException ex) {
            throw new NegocioException("error al imprimir la informacion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        tituloLbl = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        btnConsultarHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaComprobante = new javax.swing.JTextArea();
        lblCambiarEstatus = new javax.swing.JLabel();
        btnConfirmarCambio = new javax.swing.JButton();
        lblCambiarEstatus1 = new javax.swing.JLabel();
        comboBoxEstatus1 = new javax.swing.JComboBox<>();
        comboBoxCuentas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1077, 630));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setName("Separador"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(1077, 2));

        tituloLbl.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        tituloLbl.setText("CONSULTA DE PRÉSTAMO");

        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaanterior2.png"))); // NOI18N
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        btnConsultarHistorial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConsultarHistorial.setText("Consultar Historial");
        btnConsultarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHistorialActionPerformed(evt);
            }
        });

        txtAreaComprobante.setColumns(20);
        txtAreaComprobante.setRows(5);
        txtAreaComprobante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtAreaComprobante);

        lblCambiarEstatus.setBackground(new java.awt.Color(255, 255, 255));
        lblCambiarEstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCambiarEstatus.setText("Cambiar estatus:");

        btnConfirmarCambio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmarCambio.setText("Confirmar cambio");
        btnConfirmarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCambioActionPerformed(evt);
            }
        });

        lblCambiarEstatus1.setBackground(new java.awt.Color(255, 255, 255));
        lblCambiarEstatus1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCambiarEstatus1.setText("Cuentas Departamento:");

        comboBoxEstatus1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxEstatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RECHAZADO", "AUTORIZADO", "PAGADO", "PAGADO PARCIALMENTE", "COMPLETADO" }));

        comboBoxCuentas.setBackground(new java.awt.Color(153, 153, 153));
        comboBoxCuentas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        comboBoxCuentas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCambiarEstatus)
                                    .addComponent(lblCambiarEstatus1)))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarHistorial)
                                    .addComponent(btnConfirmarCambio)))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxEstatus1, 0, 382, Short.MAX_VALUE)
                                    .addComponent(comboBoxCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(tituloLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCambiarEstatus1)
                            .addComponent(comboBoxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCambiarEstatus)
                            .addComponent(comboBoxEstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnConfirmarCambio)
                        .addGap(43, 43, 43)
                        .addComponent(btnConsultarHistorial))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarCambioActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        adminPrestamosFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnConsultarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHistorialActionPerformed
        // TODO add your handling code here:
        new ConsultarHistorialFrm(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultarHistorialActionPerformed

    private void comboBoxCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCuentasActionPerformed

    }//GEN-LAST:event_comboBoxCuentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarCambio;
    private javax.swing.JButton btnConsultarHistorial;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JComboBox comboBoxCuentas;
    private javax.swing.JComboBox<String> comboBoxEstatus1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambiarEstatus;
    private javax.swing.JLabel lblCambiarEstatus1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JTextArea txtAreaComprobante;
    // End of variables declaration//GEN-END:variables
}
