/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemagestorprestamos.presentacion;

import itson.sistemasgestorprestamos.Negocio.NegocioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saula
 */
public class MenuJefeForm extends javax.swing.JFrame {
    
    private InicioSesionFrm inicioFrm;

    /**
     * Creates new form MenuJefeForm
     */
    public MenuJefeForm(InicioSesionFrm inicioFrm) {
        initComponents();
        this.inicioFrm = inicioFrm;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdministrarCuentasDpto = new javax.swing.JButton();
        btnAdministrarEmpleados = new javax.swing.JButton();
        btnAutorizarPrestamos = new javax.swing.JButton();
        btnAdminEstatusAbonos = new javax.swing.JButton();
        btnMenuEmpleados = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MENU ADMINISTRADOR");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnAdministrarCuentasDpto.setBackground(new java.awt.Color(200, 200, 200));
        btnAdministrarCuentasDpto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAdministrarCuentasDpto.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarCuentasDpto.setText("ADMINISTRAR CUENTAS DPTO");
        btnAdministrarCuentasDpto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdministrarCuentasDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarCuentasDptoActionPerformed(evt);
            }
        });

        btnAdministrarEmpleados.setBackground(new java.awt.Color(200, 200, 200));
        btnAdministrarEmpleados.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAdministrarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarEmpleados.setText("ADMINISTRAR EMPLEADOS");
        btnAdministrarEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarEmpleadosActionPerformed(evt);
            }
        });

        btnAutorizarPrestamos.setBackground(new java.awt.Color(200, 200, 200));
        btnAutorizarPrestamos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAutorizarPrestamos.setForeground(new java.awt.Color(0, 0, 0));
        btnAutorizarPrestamos.setText("AUTORIZAR PRESTAMOS");
        btnAutorizarPrestamos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAutorizarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorizarPrestamosActionPerformed(evt);
            }
        });

        btnAdminEstatusAbonos.setBackground(new java.awt.Color(200, 200, 200));
        btnAdminEstatusAbonos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAdminEstatusAbonos.setForeground(new java.awt.Color(0, 0, 0));
        btnAdminEstatusAbonos.setText("ADMINISTRAR ABONOS");
        btnAdminEstatusAbonos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdminEstatusAbonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminEstatusAbonosActionPerformed(evt);
            }
        });

        btnMenuEmpleados.setBackground(new java.awt.Color(200, 200, 200));
        btnMenuEmpleados.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnMenuEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnMenuEmpleados.setText("MENU DE EMPLEADOS");
        btnMenuEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEmpleadosActionPerformed(evt);
            }
        });

        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaanterior2.png"))); // NOI18N
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 204, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(208, 208, 208))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdministrarCuentasDpto, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdministrarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAutorizarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdminEstatusAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMenuEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(304, 304, 304))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdministrarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAdministrarCuentasDpto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAutorizarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAdminEstatusAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMenuEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarCuentasDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarCuentasDptoActionPerformed
        // TODO add your handling code here:
        new AdministrarCuentasDepartamentosFrm(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdministrarCuentasDptoActionPerformed

    private void btnAutorizarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorizarPrestamosActionPerformed
        try {
            new AdministrarPrestamosFrm(this).setVisible(true);
        } catch (NegocioException ex) {
            Logger.getLogger(MenuJefeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAutorizarPrestamosActionPerformed

    private void btnAdminEstatusAbonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminEstatusAbonosActionPerformed
        AdministrarAbonosFrm abonosFrm = null;
        try {
            new AdministrarAbonosFrm(this).setVisible(true);
            this.setVisible(false);
        } catch (NegocioException ex) {
            Logger.getLogger(MenuJefeForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error al abrir la ventana de abonos");
        }
    }//GEN-LAST:event_btnAdminEstatusAbonosActionPerformed

    private void btnMenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEmpleadosActionPerformed
        new MenuEmpleadoFrm(inicioFrm).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuEmpleadosActionPerformed

    private void btnAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarEmpleadosActionPerformed
        // TODO add your handling code here:
        AdministrarEmpleadosFrm ventana;
        try {
            
            new AdministrarEmpleadosFrm(this).setVisible(true);
            this.setVisible(false);
        } catch (NegocioException ex) {
            Logger.getLogger(MenuJefeForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error al abrir la ventana de empleados");
        }

    }//GEN-LAST:event_btnAdministrarEmpleadosActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        inicioFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminEstatusAbonos;
    private javax.swing.JButton btnAdministrarCuentasDpto;
    private javax.swing.JButton btnAdministrarEmpleados;
    private javax.swing.JButton btnAutorizarPrestamos;
    private javax.swing.JButton btnMenuEmpleados;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
